### ISSUE TITLE
Metrics returning an object instead of simple numeric value

### ISSUE THREAD

**Issue by summerville** [rarestep/metrics-closeio#2]
Looks like all the metrics are returning an _object_ instead of a _number_. For instance, the `"closeio leads created last week"` metric returns `{"15 minutes ago":120}` instead of just `120` and `"closeio active opportunities expected value"` metric returns `{"19 minutes ago":24370736}` instead of just `24370736`.

Seems like some additional logic might be needed on `line 62`:

```
metrics.set(key, results[prop])
```

**Comment by aptinio** [comment]
I couldn't reproduce this. Here's what I get:

```
> var Metrics = require('metrics')
undefined

> var closeio = require('metrics-closeio')
undefined

> var metrics = Metrics()
undefined

> metrics.every('2m', closeio(process.env.CLOSEIO_API_KEY))
{ metrics: { 'closeio won opportunities value this month by user': { _values: [Object], _events: {} } },
  intervals: 
   [ { _idleTimeout: 120000,
       _idlePrev: [Object],
       _idleNext: [Object],
       _idleStart: 5994304,
       _onTimeout: [Function: wrapper],
       _repeat: true,
       domain: [Object] } ],
  _events: {} }

> metrics.keys()
[ 'closeio won opportunities value this month by user',
  'closeio opportunities created last week',
  'closeio opportunities created 2 weeks ago',
  'closeio leads created last week',
  'closeio leads created 2 weeks ago',
  'closeio active opportunities total value',
  'closeio active opportunities expected value' ]

> metrics.get('closeio active opportunities expected value').latest()
24285236

> metrics.get('closeio leads created last week').latest()
110

> metrics.get('closeio won opportunities value this month by user').latest()
{ user_2sVfPGs0EUNZTgaPUNOznjZBUSIsSysLIO0ijy1U00v: { name: 'Matt Chapman', value: 51500 } }
```

**Comment by summerville** [comment]
Ah, must be the `latest()` call you're doing. Here's how I'm actually using the Closeio metrics in our Dashboard app:

``` javascript
var closeioMetrics = Metrics()
  .every('30m', closeio(process.env.CLOSEIO_API_KEY))
  .use(function (metrics) {
    metrics.on('closeio leads created last week', 'closeio leads created 2 weeks ago',
        function (val1, val2) {
          geckoboard(process.env.WID_LEADS_CREATED_LAST_WEEK)
              .percentageChange(val1, val2);
        });
  });
```

That's the way the other metrics plugins work. Think we can make it where the `latest()` call isn't necessary? I could just added it to the end of `val1` and `val2` as well I suppose...

**Comment by aptinio** [comment]
I don't think calling `latest()` should be necessary. I'd like this to work just like the other plugins. Let me check again.

**Comment by aptinio** [comment]
It seems that there has been a change in **metric**'s API: segmentio/metrics@f0f94b2e9873f8f078588373efaa78f608d7b5da

Instances of `Metric` are now passed to the `on` callback, instead of values.

**Comment by aptinio** [comment]
I suggest we update the `metrics` package and add calls to `latest()` in rarestep/dashboard

**Comment by summerville** [comment]
Ah, nice find. Hadn't seen that update. I'll make the changes and will keep you posted. Thanks Aaron!

**Comment by summerville** [comment]
Works like a champ now. Thanks!
